### ISSUE TITLE
Publish disassembly on GitHub pages

### ISSUE THREAD

**Issue by skoolkid** [Ritchie333/deathchase#1]
This disassembly should be published on GitHub Pages so it can be browsed online.

https://help.github.com/en/articles/configuring-a-publishing-source-for-github-pages#enabling-github-pages-to-publish-your-site-from-master-or-gh-pages

Then, add a README.md with a link to the published disassembly.

**Comment by Ritchie333** [comment]
Done. (Sorry about the five year wait!)

**Comment by Ritchie333** [comment]
Disassembly now published online https://ritchie333.github.io/deathchase
