### ISSUE TITLE
Does EI followed by DI really wait for NMI?

### ISSUE THREAD

**Issue by chupocro** [Ritchie333/deathchase#2]
The code at #66D3 is:

```
663D 	EI 	; Wait for NMI to fire to stop screen flicker
663E 	DI
```

Why would these istructions cause the Z80 to wait for a NMI? Does Spectrum (without adding some interface) even generates non maskable interrupt signals? IIRC, the NMI interrupt handler in Spectrum's ROM has a bug causing the routine at #0066 would jump to the address pointed by the vector if it **is** zero (which would reset the computer) and executing RETN if the vector is **not** zero (instead the other way round).

The instructions:
```

EI
HALT
DI
```

would wait for a **maskable** interrupt and could be used in screen update routine to start updating the video memory during vertical blank period to avoid flickering.

**Comment by Ritchie333** [comment]
Hi, just revisiting these disassemblies now. (Sorry about the 3+ year wait)

I tried replacing the EI / DI instructions with NOP and nothing appeared to happen. So it might be either it's something specific to an early issue Spectrum that doesn't happen with an emulator, an attempt to detect screen refresh, or just something that didn't break anything that wasn't worth fixing.

In any case, I've updated the documentation.
